# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Xenia Sitterer
title_seperator: "|"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  My website for information about me and the stuff I make. 
github_username: "sciclone1984"
minimal_mistakes_skin: "neon"
search: true
locale: "en-US"
repository: "sciclone1984/sciclone1984.github.io"
logo: "/assets/images/masthead.png"
og_image: "/assets/images/masthead.png"
social:
  type: "Person"
  links:
    - "https://www.linkedin.com/in/alex-sitterer/"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Xenia Sitterer"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Privacy Advocate with a Bachelors in Cybersecurity and Networks. Currently building something from a mixture of words, code, and physical objects."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sciclone1984"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/xenia-sitterer/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sciclone1984"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/xenia-sitterer/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true
  # _portfolio
  - scope:
      path: "_projects"
      type: projects
    values: 
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  projects:
    output: true
    permalink: /:collection/:path/
